CREATE TABLE `USER`(
    `INTERNAL_ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(64) NOT NULL,
    `EXTERNAL_ID` INT NOT NULL,
    `CREATION_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`INTERNAL_ID`),
    UNIQUE (`EXTERNAL_ID`)
)

CREATE TABLE `PAYMENT`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `FOR_MONTH` INT NOT NULL,
    `FOR_YEAR` INT NOT NULL,
    `FK_USER_ID` INT,
    `CREATION_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY(`ID`),
    PRIMARY KEY(
        `FK_USER_ID`,
        `FOR_MONTH`,
        `FOR_YEAR`
    ),
    FOREIGN KEY(`FK_USER_ID`) REFERENCES `USER`(`INTERNAL_ID`)
)

CREATE TABLE `ADMIN`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(64) NOT NULL,
    `PASSWORD` VARCHAR(64) NOT NULL,
    PRIMARY KEY(`ID`),
    UNIQUE (`USERNAME`)
)

INSERT INTO `USER` (`NAME`, `EXTERNAL_ID`) VALUES
('Dimityr Antonov', 121),
('Anton Antonov', 122),
('Ivan Antonov', 123),
('Silviq Kateva', 124),
('Nencho Toshev', 125),
('Odette Cogan', 126),
('Wendell Belvin', 141),
('Armando Tinney', 142),
('Richelle Nevins', 143),
('Nelia Scaggs', 144)

INSERT INTO `ADMIN` (`USERNAME`, `PASSWORD`) VALUES ('aruseff', PASSWORD('adminpass'))
INSERT INTO `ADMIN` (`USERNAME`, `PASSWORD`) VALUES ('hterziev', PASSWORD('adminpass'))